#!/usr/bin/env python
import argparse
import os
import os.path as path

def install(args):
    home = os.environ['HOME']
    dotbase = os.getcwd()

    for topic in os.listdir(dotbase):
        topdir = path.join(dotbase, topic)

        # Ignore the file if it's not a folder, or if it's hidden
        if not path.isdir(topdir) or topic[0] == '.':
            continue

        for dotfile in os.listdir(topdir):
            dotpath = path.join(topdir, dotfile)
            target = path.join(home, '.' + dotfile)

            os.symlink(dotpath, target)

def uninstall(args):
    home = os.environ['HOME']
    dotbase = os.getcwd()

    for file in os.listdir(home):
        fpath = path.join(home, file)
        if not path.islink(fpath):
            continue

        source = path.realpath(fpath)
        if not source.startswith(dotbase):
            continue

        os.remove(fpath)


DOT_DESCRIPTION = ('This script is used to TAKE OVER THE WORLD.. err.. '
                    'manage dotfiles')
INSTALL_DESCRIPTION = 'Install the dotfiles in yo home directory brah'
UNINSTALL_DESCRIPTION = 'Get rid of the dot files that symlink here'

def main():
    # Parse arguments
    parser = argparse.ArgumentParser(description=DOT_DESCRIPTION)
    commands = parser.add_subparsers(metavar='command',
                                    help='Available commands are: %(choices)s')

    ## Install subparser
    install_parser = commands.add_parser('install',
                                        description=INSTALL_DESCRIPTION)
    install_parser.set_defaults(func=install)

    # Uninstall subparser
    uninstall_parser = commands.add_parser('uninstall',
                                          description=UNINSTALL_DESCRIPTION)
    uninstall_parser.set_defaults(func=uninstall)

    args = parser.parse_args()
    args.func(args)

if __name__ == '__main__':
    main()
